package  {
	
	public class ItemDefinitions {
		public static var main:Main;
		
		/**
		 * Short for "get stat" - gets the given player stat, resource, etc.
		 */
		public static function getStat(stat:String):int {
			if (main == null || main.player == null) {
				trace("WARNING: Main or Player not found when trying to call ItemDefinitions.gs()!");
				return -1;
			}
			return main.player.getStat(stat);
		}
		
		
		public static const definitions:Object = {
			"Cerulean Hat"		: {	name		: "Cerulean Hat",
									short		: "A strange pointed wizard's hat.",
									long		: "It's colored cerulean blue and seems to give off a magical, other-worldly aura. Increases max HP based on intelligence and maximum mana.",
									value		: 42,
									equip		: true,
									head		: true,
									effects		: [function():Array { return ["maxHealth", Math.round(getStat("int") * 3 + getStat("maxMana") * .2) as int] }] },
			"Red Potion"		: {	name		: "Red Potion",
									short		: "Recovers 50 health.",
									long		: "A red potion with basic healing properties.",
									value		: 10,
									effects		: [function():Array { return ["currHealth", 50] },
												   function():Array { return ["currCapacity", 10] }] },
			"Orange Potion" 	: {	name		: "Orange Potion",
									short		: "Recovers 100 health.",
									long		: "An orange potion with standard healing properties.",
									value		: 25,
									effects		: [function():Array { return ["currHealth", 100] },
												   function():Array { return ["currCapacity", 25] }] },
			"Yellow Potion" 	: {	name		: "Yellow Potion",
									short		: "Recovers 250 health.",
									long		: "A yellow potion with potent healing properties.",
									value		: 50,
									effects		: [function():Array { return ["currHealth", 250] },
												   function():Array { return ["currCapacity", 50] }] },
			"White Potion" 		: {	name		: "White Potion",
									short		: "Recovers 500 health.",
									long		: "A white potion with powerful healing properties.",
									value		: 100,
									effects		: [function():Array { return ["currHealth", 500] },
												   function():Array { return ["currCapacity", 100] }] },
			"Blue Potion" 		: {	name		: "Blue Potion",
									short		: "Restores 50 mana.",
									long		: "A blue potion with basic regenerative properties.",
									value		: 50,
									effects		: [function():Array { return ["currMana", 50] },
												   function():Array { return ["currCapacity", 25] }] },
			"Violet Potion" 	: {	name		: "Violet Potion",
									short		: "Restores 250 mana.",
									long		: "A violet potion with potent regenerative properties.",
									value		: 100,
									effects		: [function():Array { return ["currMana", 250] },
												   function():Array { return ["currCapacity", 100] }] },
											
			"Mutton Loin"		: {	name		: "Mutton Loin",
									short		: "An enormous cut of meat taken from below a sheep's entire rib cage.",
									long		: "This heavily marbled slab of meat has been thick-cut and seasoned to perfection before being seared and grilled medium rare. Normally, the loin is a very lean cut. However, the current state of rampant vegetation has left the fields a veritable buffet for sheep and other livestock, leaving them fattened to absurd proportions.",
									value		: 15,
									effects		: [//function():Array { return ["str", 10] },//function():Array { return ["atk", 5] },
												   function():Array { return ["currCapacity", 50] }] },
			"Roast Chicken"		: {	name		: "Roast Chicken",
									short		: "A whole roast chicken.",
									long		: "Naturally a lean meat, this chicken, more akin to a turkey and big enough to be served on a shield, has seen better days. It has been baked until golden brown with a blend of exotic herbs and spices fused into its flesh that permeates a rich, savory aroma. The skin was basted in the chicken's very own juices, leaving the surface crunchy and gleaming.",
									value		: 25,
									effects		: [//function():Array { return ["atk", 10] },
												   function():Array { return ["currCapacity", 80] } ] },
			"Pork Haunch"		: {	name		: "Pork Haunch",
									//short		: "An enormous honey-glazed ham.",
									//long		: "It's practically oozing its savory juices out of its crispy flesh.",
									short		: "An enormous hunk of raw pork.",
									long		: "The succulent hip of a pig, so massive that the cut itself would dwarf an entire pig from only a few short years ago. The fat content has gone far beyond that of simple marbling and is rippling, quite literally, with inch-thick veins of blubber. In fact, it's probably more fat than meat with a comparative toothpick of a bone lodged somewhere deep inside.",
									value		: 50,
									effects		: [//function():Array { return ["atk", 10] },
												   function():Array { return ["currCapacity", 150] }] },
										
			"Knife"				: {	name		: "Knife",
									short		: "A simple knife.",
									long		: "You'll have a hard time cutting through just about anything with a blade this dull.",
									value		: 15,
									equip		: true,
									weapon		: true,
									effects		: [function():Array { return ["atk", 7] }] },
			"Sword" 			: {	name		: "Sword",
									short		: "A basic sword.",
									long		: "Standard issue for new recruits of the town guard. No frills and nothing fancy, just a simple sword.",
									value		: 20,
									equip		: true,
									weapon		: true,
									effects		: [function():Array { return ["atk", 10] }] },
			"Falchion" 			: {	name		: "Falchion",
									short		: "A sword with a keen, slightly curved edge meant for slashing.",
									long		: "The broad single-edged blade on this sword is reminiscent of distant eastern influences. As a result, it had previously been attributed to those possessing more agility than strength.",
									value		: 30,
									equip		: true,
									weapon		: true,
									effects		: [function():Array { return ["atk", 15] }] },
			"Rapier" 			: {	name		: "Rapier",
									short		: "A slender sword most notable for its elegant blade and crossguard.",
									long		: "Fencers have been difficult to come across as of late, but those who retain their discipline are not to be trifled with. A thrusting weapon not meant for those with leaden feet.",
									value		: 40,
									equip		: true,
									weapon		: true,
									effects		: [function():Array { return ["atk", 20] }] },
			"Sabre" 			: {	name		: "Sabre",
									short		: "A heavy sword with a curved, single-edged blade.",
									long		: "The sabre is commonly used among both foot soldiers and cavalry alike. It is favored for its reliability as an effective slashing weapon while its sizeable hand guard provides adequate protection against foes as well.",
									value		: 65,
									equip		: true,
									weapon		: true,
									effects		: [function():Array { return ["atk", 30] }] },
			"Cutlass" 			: {	name		: "Cutlass",
									short		: "A short, broad slashing sword.",
									long		: "Popularized by its use out at sea, the cutlass is a heavy blade whose strength belies its size. Those of seafaring towns know it as the weapon of choice for pirates who seek to plunder their bountiful booty.",
									value		: 110,
									equip		: true,
									weapon		: true,
									effects		: [function():Array { return ["atk", 45] }] },
			"Katana" 			: {	name		: "Katana",
									short		: "A long curved blade with an exquisitely fine edge.",
									long		: "Originating from the far east, the katana requires extensive study in order utilize effectively. Legend has it that only the most skilled warriors, tempered and disciplined by a lifetime of grueling training, were allowed to even wield this weapon.",
									value		: 140,
									equip		: true,
									weapon		: true,
									effects		: [function():Array { return ["atk", 55] }] },
			"Flamberge" 		: {	name		: "Flamberge",
									short		: "A powerful sword with a characteristically undulating and wavy blade.",
									long		: "The flamberge, or flame blade, gets its name from its uniquely flame-like blade. Not only is this an effective, versatile weapon, the waves in its blade are also known to cause unpleasant vibrations to assailants when used to parry attacks. More recently though, it has been noted that such vibrations have become more distracting than unpleasant.",
									value		: 200,
									equip		: true,
									weapon		: true,
									effects		: [function():Array { return ["atk", 70] }] },
			"Lance" 			: {	name		: "Lance",
									short		: "A common type of spear meant to be used on horseback.",
									long		: "Typically given to cavalry for charging at enemy force. Given its weight and unwieldy size, lances are difficult to use on foot. However, given recent trends, some adventurers seem to prefer weapons that can attest to their own size.",
									value		: 125,
									equip		: true,
									weapon		: true,
									twoHanded	: true,
									effects		: [function():Array { return ["atk", 50] }] },
			"Halberd" 			: {	name		: "Halberd",
									short		: "A spear with a large axe-like blade at the end.",
									long		: "As a result, this weapon is considerably heavier than most other spears, much like those who seem to be using it these days. Commonly used in regimental combat, the halberd is mostly found in the hands of foot soldiers due to its long reach.",
									value		: 210,
									equip		: true,
									weapon		: true,
									twoHanded	: true,
									effects		: [function():Array { return ["atk", 90] }] },
			"Axe" 				: {	name		: "Axe",
									short		: "A simple axe.",
									long		: "A basic axe with a long handle meant for two hands.",
									value		: 35,
									equip		: true,
									weapon		: true,
									twoHanded	: true,
									effects		: [function():Array { return ["atk", 13] }] },
			"Flail" 			: {	name		: "Flail",
									short		: "A spiked metal ball affixed to a handle by a chain.",
									long		: "While a brutal and intimidating weapon for bludgeoning, the flail can easily backfire if used without caution. The chain is longer than one might think, and a clumsy warrior may find a painful surprise waiting for him at the end of his swing.",
									value		: 45,
									equip		: true,
									weapon		: true,
									twoHanded	: true,
									effects		: [function():Array { return ["atk", 20] }] },
											
			"Hat"				: {	name		: "Hat",
									short		: "A simple hat.",
									long		: "It's better than nothing.",
									value		: 15,
									equip		: true,
									head		: true,
									effects		: [function():Array { return ["def", 1] }] },
			"Cotton Shirt"		: {	name		: "Cotton Shirt",
									short		: "A simple shirt.",
									long		: "Normal, day-to-day clothing. It provides little means of defense.",
									value		: 10,
									equip		: true,
									torso		: true,
									effects		: [function():Array { return ["def", 3] }] },
			"Denim Pants"		: {	name		: "Denim Pants",
									short		: "A simple pair of pants.",
									long		: "Nothing too special about jeans.",
									value		: 20,
									equip		: true,
									legs		: true,
									effects		: [function():Array { return ["def", 2] }] },
			"Shoes"				: {	name		: "Shoes",
									short		: "A simple pair of shoes.",
									long		: "Can't leave home without 'em!",
									value		: 25,
									equip		: true,
									feet		: true,
									effects		: [function():Array { return ["def", 5] }] },
			"Guard"				: {	name		: "Guard",
									short		: "A simple shield.",
									long		: "Effectively defends against incoming attacks.",
									value		: 40,
									equip		: true,
									shield		: true,
									effects		: [function():Array { return ["def", 10] }] }
		};
		
		public static function getItem(name:String):Item {
			return new Item(definitions[name]);
		}
	}
}
